# Generated by cpp11: do not edit by hand

acquire_immunity_cpp <- function(exposure, u, d) {
  .Call(`_malariavaxTrials_acquire_immunity_cpp`, exposure, u, d)
}

get_b_cpp <- function(ib, b0, b1, ib0, kb) {
  .Call(`_malariavaxTrials_get_b_cpp`, ib, b0, b1, ib0, kb)
}

get_phi_cpp <- function(ica, icm, phi0, phi1, ic0, kc) {
  .Call(`_malariavaxTrials_get_phi_cpp`, ica, icm, phi0, phi1, ic0, kc)
}
